version: 2.1

orbs:
  ipsec: danackerson/ipsec@0.2.1

jobs:
  build:
    docker:
      - image: golang:alpine
    working_directory: /go/src/github.com/danackerson/bender-slackbot
    steps:
      - checkout
      - run:
          name: "Fetch dependencies and build bender app"
          command: |
            apk add -U --no-cache curl build-base git libc6-compat
            go get -t -d -v ./...
            env GOOS=linux GOARCH=arm GOARM=7 go build bender.go
      - persist_to_workspace:
          root: /go/src/github.com/danackerson/bender-slackbot
          paths:
            - bender
            - Dockerfile

commands:
  prepare_deploy_script:
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Build & push docker image"
          command: |
            export DOCKER_TAG=danackerson/bender:vc$CIRCLE_BUILD_NUM

            mv /tmp/bender /tmp/Dockerfile .
            docker build . --compress -t $DOCKER_TAG

            docker login -u $CTX_DOCKER_USER -p $CTX_DOCKER_PASS
            docker tag $DOCKER_TAG danackerson/bender:latest
            docker push $DOCKER_TAG
            docker push danackerson/bender:latest

      - run:
          name: "Prepare deploy script"
          command: |
            cat \<<EOF >deploy_script.sh
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "\
            docker login -u $CTX_DOCKER_USER -p \"$CTX_DOCKER_PASS\" && \
            docker pull danackerson/bender:$CIRCLE_BUILD_NUM && \
            docker rm -f bender || true && \
            docker run -d --restart=always \
              -e CTX_DIGITALOCEAN_FIREWALL=$CTX_DIGITALOCEAN_FIREWALL \
              -e doFloatingIP=$doFloatingIP \
              -e homeDomain=$homeDomain \
              -e CTX_CIRCLECI_API_TOKEN=$CTX_CIRCLECI_API_TOKEN \
              -e raspberryPIIP=$raspberryPIIP \
              -e slackReportChannel=$slackReportChannel \
              -e piUser=$piUser -e piPass=$piPass \
              -e CTX_DIGITALOCEAN_TOKEN=$CTX_DIGITALOCEAN_TOKEN \
              -e CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM \
              -e CTX_SLACK_API_TOKEN=$CTX_SLACK_API_TOKEN \
              -e CTX_DIGITALOCEAN_SPACES_KEY=$CTX_DIGITALOCEAN_SPACES_KEY \
              -e CTX_DIGITALOCEAN_SPACES_SECRET=$CTX_DIGITALOCEAN_SPACES_SECRET \
              -e CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC=$CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC \
              -e CTX_JOIN_API_KEY=$CTX_JOIN_API_KEY \
              --name bender danackerson/bender:$CIRCLE_BUILD_NUM"
            EOF

            chmod u+x deploy_script.sh

workflows:
  build-deploy:
    jobs:
        - build:
            context: org-global
        - ipsec/remote-deploy:
            context: org-global
            requires:
              - build
            pre-steps:
              - prepare_deploy_script
