version: 2.1

jobs:
  build:
    docker:
      - image: golang:alpine
    working_directory: /go/src/github.com/danackerson/bender-slackbot
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Install Docker CE"
          command: |
            apk add -U curl build-base git libc6-compat
            curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$CTX_DOCKER_ENGINE_VERSION.tgz && tar --strip-components=1 -xvzf docker-$CTX_DOCKER_ENGINE_VERSION.tgz -C /usr/local/bin
            rm docker-$CTX_DOCKER_ENGINE_VERSION.tgz && rm -f /var/cache/apk/*
      - run:
          name: "Build & push docker image"
          command: |
            go get -t -d -v ./...
            env GOOS=linux GOARCH=386 go build bender.go

            echo vc$CIRCLE_BUILD_NUM > last_docker_push

            docker build --compress -t danackerson/bender:vc$CIRCLE_BUILD_NUM .
            docker login -u $CTX_DOCKER_USER -p $CTX_DOCKER_PASS
            docker tag danackerson/bender:vc$CIRCLE_BUILD_NUM danackerson/bender:latest
            docker push danackerson/bender:vc$CIRCLE_BUILD_NUM
            docker push danackerson/bender:latest
      - persist_to_workspace:
          root: /go/src/github.com/danackerson/bender-slackbot
          paths:
            - bender
            - run_bender.sh

  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/deploy
    steps:
      - run:
          name: Store Service Accounts
          command: |
            apk -u add jq
            echo $CTX_GOOGLE_DEPLOY_SERVICE_JSON > ${HOME}/gcloud-service-key.json
            chmod 600 $HOME/gcloud-service-key.json

            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${CTX_GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone europe-west3-c
      - run:
          name: Prepare deploy network access
          command: |
            ORIG_RANGE=`gcloud compute firewall-rules describe default-allow-ssh \
              --format=json | jq -r '.sourceRanges | @csv'`
            ORIG_RANGE=`echo ${ORIG_RANGE//\"}`
            echo $ORIG_RANGE > /tmp/orig_range.txt

            export DEPLOY_IP=`curl -s https://icanhazip.com`
            gcloud compute firewall-rules update default-allow-ssh \
              --source-ranges=$ORIG_RANGE,$DEPLOY_IP
      - checkout
      - run:
          name: "Prepare env secrets & deploy K8S config"
          command: |
            export CIRCLE_BUILD_NUM_B64=`echo -n '$CIRCLE_BUILD_NUM' | base64`
            sed -i -e "s@{{CIRCLE_BUILD_NUM_B64}}@$CIRCLE_BUILD_NUM_B64@" bender.yml

            export homeDomain_B64=`echo -n '$homeDomain' | base64`
            sed -i -e "s@{{homeDomain_B64}}@$homeDomain_B64@" bender.yml

            export slackReportChannel_B64=`echo -n '$slackReportChannel' | base64`
            sed -i -e "s@{{slackReportChannel_B64}}@$slackReportChannel_B64@" bender.yml

            export PLEX_TOKEN_B64=`echo -n '$PLEX_TOKEN' | base64`
            sed -i -e "s@{{PLEX_TOKEN_B64}}@$PLEX_TOKEN_B64@" bender.yml

            export CTX_CIRCLECI_API_TOKEN_B64=`echo -n '$CTX_CIRCLECI_API_TOKEN' | base64`
            sed -i -e "s@{{CTX_CIRCLECI_API_TOKEN_B64}}@$CTX_CIRCLECI_API_TOKEN_B64@" bender.yml

            export CTX_DIGITALOCEAN_TOKEN_B64=`echo -n '$CTX_DIGITALOCEAN_TOKEN' | base64`
            sed -i -e "s@{{CTX_DIGITALOCEAN_TOKEN_B64}}@$CTX_DIGITALOCEAN_TOKEN_B64@" bender.yml

            export CTX_SLACK_API_TOKEN_B64=`echo -n '$CTX_SLACK_API_TOKEN' | base64`
            sed -i -e "s@{{CTX_SLACK_API_TOKEN_B64}}@$CTX_SLACK_API_TOKEN_B64@" bender.yml

            export CTX_JOIN_API_KEY_B64=`echo -n '$CTX_JOIN_API_KEY' | base64`
            sed -i -e "s@{{CTX_JOIN_API_KEY_B64}}@$CTX_JOIN_API_KEY_B64@" bender.yml

            export CTX_VPNC_GATEWAY_B64=`echo -n '$CTX_VPNC_GATEWAY' | base64`
            sed -i -e "s@{{CTX_VPNC_GATEWAY_B64}}@$CTX_VPNC_GATEWAY_B64@" bender.yml

            export CTX_DROPBOX_ACCESS_TOKEN_B64=`echo -n '$CTX_DROPBOX_ACCESS_TOKEN' | base64`
            sed -i -e "s@{{CTX_DROPBOX_ACCESS_TOKEN_B64}}@$CTX_DROPBOX_ACCESS_TOKEN_B64@" bender.yml

            export CTX_SERVER_DEPLOY_SECRET_B64=`echo -n '$CTX_SERVER_DEPLOY_SECRET' | base64`
            sed -i -e "s@{{CTX_SERVER_DEPLOY_SECRET_B64}}@$CTX_SERVER_DEPLOY_SECRET_B64@" bender.yml

            scp -o StrictHostKeyChecking=no bender.yml ackersond@$K8S_SERVER:~/
            ssh ackersond@$K8S_SERVER -- "sudo kubectl apply -f bender.yml"
      - run:
          name: Remove deploy network access
          command: |
            export ORIG_RANGE=`cat /tmp/orig_range.txt`
            if [ ! -z "$ORIG_RANGE" ]; then
              gcloud compute firewall-rules update default-allow-ssh \
                --source-ranges=$ORIG_RANGE
            fi
          when: always

workflows:
  build-deploy:
    jobs:
        - build:
            context: org-global
        - deploy:
            context: org-global
            requires:
              - build
