version: 2.1

orbs:
  ipsec: danackerson/ipsec@dev:13

jobs:
  build:
    docker:
      - image: golang:alpine
    working_directory: /go/src/github.com/danackerson/bender-slackbot
    steps:
      - checkout
      - run:
          name: "Fetch dependencies and build bender app"
          command: |
            apk add -U --no-cache curl build-base git libc6-compat
            go get -t -d -v ./...
            env GOOS=linux GOARCH=arm GOARM=7 go build bender.go
      - persist_to_workspace:
          root: /go/src/github.com/danackerson/bender-slackbot
          paths:
            - bender
            - run_bender.sh

commands:
  prepare_deploy_script:
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Prepare deploy script"
          command: |
            ls -lrt /tmp/

            cat \<<EOF >deploy_script.sh
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "\
              mkdir bender_app || true"
            scp /tmp/bender /tmp/run_bender.sh \
              $SSH_USER@$SSH_HOST:~/bender_app/
            ssh $SSH_USER@$SSH_HOST "docker rm -f bender || true && \
            docker run -d --restart=always \
              -v ~/bender_app:/tmp/ \
              -e CTX_DIGITALOCEAN_FIREWALL=$CTX_DIGITALOCEAN_FIREWALL \
              -e doFloatingIP=$doFloatingIP \
              -e homeDomain=$homeDomain \
              -e CTX_CIRCLECI_API_TOKEN=$CTX_CIRCLECI_API_TOKEN \
              -e raspberryPIIP=$raspberryPIIP \
              -e slackReportChannel=$slackReportChannel \
              -e piUser=$piUser -e piPass=$piPass \
              -e CTX_DIGITALOCEAN_TOKEN=$CTX_DIGITALOCEAN_TOKEN \
              -e CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM \
              -e CTX_SLACK_API_TOKEN=$CTX_SLACK_API_TOKEN \
              -e CTX_DIGITALOCEAN_SPACES_KEY=$CTX_DIGITALOCEAN_SPACES_KEY \
              -e CTX_DIGITALOCEAN_SPACES_SECRET=$CTX_DIGITALOCEAN_SPACES_SECRET \
              -e CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC=$CTX_DIGITALOCEAN_SPACES_NAME_PUBLIC \
              -e CTX_JOIN_API_KEY=$CTX_JOIN_API_KEY \
              --name bender arm32v7/alpine /tmp/run_bender.sh"
            EOF

            chmod u+x deploy_script.sh

workflows:
  build-deploy:
    jobs:
        - build:
            context: org-global
        - ipsec/remote-deploy:
            context: org-global
            requires:
              - build
            pre-steps:
              - prepare_deploy_script
